### ISSUE TITLE
Request: Undo a mute or a block

### ISSUE THREAD

**Issue by dmuth** [tveastman/secateur#14]
I'd love to see the ability to undo a mute or a block of someone or their followers.

I got the app running in Docker (great job on that, BTW!), so if there is development happening in a branch, I'd be happy to test!

Thanks,

-- Doug

**Comment by tveastman** [comment]
Hi!

Yes, I think this is the most important next feature to get deployed. I recently had to manually help someone who had accidentally blocked a whole bunch of people they didn't mean to.

There are no branches other than the mainline, more or less. If you want to give such a feature a shot I can provide guidance, otherwise you have to wait for me to get around to it, which is highly depending on my limited free time :+1: 

One thing I know I need to add a page where people can set an 'until' time on all the accounts they've blocked 'forever'.

Let's say you blocked 100,000 people forever, and then regretted it. I want a button you can push that will set the 'until' for each of those blocks to a random time within the next several weeks (to spread out the unblocking to ease load on the system). That's probable what needs to be implemented first.

Later on, a page where you can actually browse all the accounts you've blocked, and unblock them as desired. That's a bit more complicated because it'd need to be searchable, filterable, and paginated, and any searches need to be carefully indexed to keep load minimal.

**Comment by dmuth** [comment]
I'd love to take a crack at it, but unfortunately I don't know Django.  It's definitely on the list of "things I'd like to learn", it's just a matter of finding hours in the day.  (And caring for my own sanity between working my day job and all the crazy things happening in the world right now.)

I looked in https://github.com/tveastman/secateur/blob/master/secateur/migrations/0001_initial.py which, as best I can tell, is where the database schema lives in a manner not unlike what SQLAlchemy uses.  I was thinking one way to go about doing this would be to have an "actions" table which holds rows for when someone/their followers are muted/blocked.  Then undoing such an action just requires a UI to display the contents of that table for that user, provide a button, and when clicked on, the reverse operation is performed.

We might as well keep this one open in the time being, and I put "learn Django" into my personal Trello Board.  I'll see if I can pick it up, but no promises. :-)

-- Doug

**Comment by tveastman** [comment]
The 'who's blocked by who' data is already there in the 'relationship' table. That's what we'll use. The tricky part is navigating the sheer number of people who have been blocked, so it'll have to be paginated and searchable using indexes.

The `secateur.app` database is big enough now that I have to tread carefully: if I expose a single operation to users that ends up with a 'sequential scan' of the table, the load will kill the server :-) so I have to be pretty careful with how any new views work!

**Comment by tveastman** [comment]
As of a few months ago there is now a page on secateur that'll let you unblock everybody you've ever blocked, it works by spreading out all the operations over the course of a month. I'll make this issue as "complete"
